[package]
name = "tensor-mesh-ipc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.14.0"
prost = "0.14.1"
serde = { version = "1.0", features = ["derive"] }
tower = "0.5.2"