[package]
name = "tensor-mesh-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
half = { version = "2.4", features = ["serde"] }
thiserror = "2.0.12"

[lib]
path = "src/lib.rs"